### ISSUE TITLE
Create the function that renders a story

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#132]
**__Task Description__**
We need to render madlibs after the inputs have been filled in.

**__Technical Considerations__**
The function will receive as arguments, (scenario, values, title, index, keys)

**__Additional Considerations__**
It should find and replace all instances of the variable word with the replacement word provided in the values argument

**Comment by PaulaR-05** [comment]
@mnichols08 I'm going to close it... okay?
