### ISSUE TITLE
Turn in the Project

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#147]
**__Task Description__**
After we have deemed our project complete and ready for turn-in, we need one person to [turn in the project](https://forms.gle/Dmhszaep2XV7vqba9)

**__Technical Considerations__**
You will need to gather all of our Discord Usernames along with the hashtag

**__Additional Considerations__**
Perhaps Mili could create a showcase video to share?

**Comment by mnichols08** [comment]
This task does not require a branch, but if we wanted to add a showcase video or something it would.

**Comment by mnichols08** [comment]
Hey Mili this is fantastic! Great work thanks for putting this together

**Comment by mnichols08** [comment]
If you want you could create a branch from development and somewhere appropriate within the Readme you could provide a link to the YouTube video :)

**Comment by PaulaR-05** [comment]
Mili, great video! I loved it

**Comment by PaulaR-05** [comment]
**Discord names**

- mNix#5589
- Nazile#5259
- Emimint#8106
- Mili#1744
- Gabriela de Paula#4224

**Comment by mnichols08** [comment]
1. What is your email address? a. ) Whoever ends up turning in the assignment can use their own email address
2. What is your Voyage? a. ) V43 
3. What is your Tier? a. ) Tier 1 - Toucans
4. What is your Team number? a. ) 9
5. What are the Discord user names of all team members **who contributed** to the project? Please enter a comma separated accont-name#nnnn values: a. ) Emimint#8106,Mili#1744,mNix#5589,Nazile#5259,Gabriela de Paula#4224
6. What is the name of the project? (If there isn't a name you can just write "no name") a. ) Mad Libs
7. Please describe the project in a sentence or two. a. ) A collaborative attempt at creating a Mad Libs Word Game as part of the Chingu Voyage program, following the Agile Methodology and the Minimum Viable Product(MVP). The game consists of one player prompting a list of words to substitute for blanks in a story before reading aloud.
8. URL of your Github repo: a. ) https://github.com/chingu-voyages/v43-tier1-team-09
9. URL of your deployed project: a. ) https://v43-tier1-team-09.netlify.app/
10. If you have a project Showcase video, what's the URL where it is located? (Remember this needs to be a public URL): a. )https://www.youtube.com/watch?v=wzQC3xtzPss
11. What tech-stack did you use for your project? (ex. React, webpack, node.js, MongoDB, etc.): a. ) Figma as a design tool, Python as a data sculpting tool, HTML5 leveraging Webpack to build SCSS and JS files following a Model View Controller structure.
12. (Optional) What was the best aspect of your team project experience? a. ) #229 
13. (Optional) What was the hardest aspect of the team project? a. ) #230 
14. (Optional) Please leave any extra comments you may have: a. ) #232 
15. On a scale of 0-10, how likely are you to recommend Chingu to a friend or colleagues? a. ) You can choose this one for yourself

Above are the answers we will need to fill out in order to turn in the project. I think we should take a moment to discuss the optional questions and I created them and links there as well. Please contribute =)

**Comment by PaulaR-05** [comment]
[PROJECT_SUBMIT_FORM.pdf](https://github.com/chingu-voyages/v43-tier1-team-09/files/11244755/PROJECT_SUBMIT_FORM.pdf)

Form Submitted ❤️🚀🙌
