### ISSUE TITLE
Update README to explain our python script

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#153]
**__Task Description__**
As titled, I think it would be phenomenal to have an extension of our readme file to mention the python script that @Emimint wrote.

**__Technical Considerations__**
We could write a little bit about how it works and  goes on within the file.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by PaulaR-05** [comment]
@Emimint We could tackle this issue together... If you write how it works I can update it on the readme file :) 
Let me know what you think :)

**Comment by PaulaR-05** [comment]
Awesome idea @mnichols08

**Comment by Emimint** [comment]
@mnichols08 @PaulaR-05 I have updated the file with comments here: https://github.com/chingu-voyages/v43-tier1-team-09/commit/8b2ba8ad0b4bcdf71bc49fc1efc4d39b41db101a

**Comment by PaulaR-05** [comment]
Thanks, Em! So, I let you guys know when I finish this task ;)
