### ISSUE TITLE
Create a new view for our team page

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#168]
**__Task Description__**
#75 has been completed so the hard part of design is finished. We now just need to implement logic to render it on screen.

**__Technical Considerations__**
It does create a new page. There is a way we could shift the top right dots off screen and shift the top left onto screen, and also shift the bottom left off screen and then shift the bottom right onto screen (this would create more interaction between the user and application and visualizing to the user they are upon a new page as well)

**__Additional Considerations__**
I would love to see the https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482 implemented on this page too

**Comment by PaulaR-05** [comment]
Great idea!

**I would love to see the https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482 implemented on this page too**
