### ISSUE TITLE
[BUG] Print.scss _ The file is not rendering the label for the blanks

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v43-tier1-team-09#186]
**Describe the bug**
The file is not rendering the label for the blanks for the Print File.

**To Reproduce**
1. Go to 'https://v43-tier1-team-09.netlify.app/'
2. Click on 'any story available
3. Scroll down to 'story page and press PRINT MAD LIB'

**Expected behavior**
As it is a print file, the user should be able to see the variables needed. 

**Screenshots**
Attached file on this task
[BUG EXAMPLE.pdf](https://github.com/chingu-voyages/v43-tier1-team-09/files/11215310/BUG.EXAMPLE.pdf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mnichols08** [comment]
I created a pull request to fix this. Please let me know if it does =)

**Comment by PaulaR-05** [comment]
@mnichols08 it worked. thank you!
