### ISSUE TITLE
[BUG] Footer does not show up in Windows 11

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#202]
**Describe the bug**
As titled for some silly reason, on Window 11, you cannot scroll down to render the header on screen.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nazile-Tag** [comment]
I checked, the footer only shows up when you scroll the mouse wheel to the bottom

**Comment by mnichols08** [comment]
Confirms to be working at work on a windows 11 machine that didn't work yesterday

I am going to close the issue thanks
