### ISSUE TITLE
Create a UI mockup

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#22]
Let's try and come up with a final UI concept by 3/21

**Comment by mnichols08** [comment]
We need a volunteer on this, please =)

**Comment by mnichols08** [comment]
https://www.figma.com/file/Px3O3bPScjpjeWjcmRivdg/v43-09-team-library?node-id=0-1&t=TGbXi9DUTwgk5dmM-0 share your email to gain collaboration

**Comment by PaulaR-05** [comment]
Here is mine: gabriela05paula@gmail.com

**Comment by emilio12345** [comment]
Should we pick some existing madlibs games and vote on which one we want to base ours on? We can vote on them the same way we are voting for the features and scenarios in that Google Sheet. From there, it might be easier to create the wireframe.

**Comment by mnichols08** [comment]
@emilio12345 that is a good idea.

**Comment by mnichols08** [comment]
We will have overlap on this with the feature idea page so be aware we should use this for explicit examples where there is something unique about another app that we might want in ours.

**Comment by mnichols08** [comment]
Should we merge (close this issue) this with the wireframe?

**Comment by PaulaR-05** [comment]
Mobile: https://www.figma.com/proto/TOdiv1fTmujFsfyL3J9TwL/Madlibs_MOBILE?node-id=1%3A5&scaling=scale-down&page-id=0%3A1



[MadLibs_v1.pdf](https://github.com/chingu-voyages/v43-tier1-team-09/files/10974684/MadLibs_v1.pdf)
