### ISSUE TITLE
Come up with your idea of a Low Fidelity Framework to Share

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#34]
Share to https://docs.google.com/spreadsheets/d/1ZIR3LV7SLhk6dOJthe_HmtMfTCK9qnqKGFl0sSPs0D8/edit#gid=1743230707 if you can please

**Comment by emilio12345** [comment]
I gave this a shot. Here's mine: https://www.figma.com/file/n5g1GTr3AAo6wbY8WdRcsq/MadLibs-User-Journey?node-id=0%3A1&t=EpFcLZTkil0YhWui-1

**Comment by mnichols08** [comment]
Thanks for your support, we can close this then =)
