### ISSUE TITLE
Write a function to determine whether or not there are offensive words or phrases and handle them

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#40]
middleware is just a fancy term for takes, does something, returns

So the function should take an argument
```
function fn(arg){
arg = `${arg}_mn`
return arg
}
```
then do something to that argument then returns it

So it would take words input by a user, and run some sort of check to determine if its a curse word or not.

**Comment by Nazile-Tag** [comment]
complicated but i will try :)

**Comment by PaulaR-05** [comment]
Hey Guys! I found it on GitHub: https://github.com/MauriceButler/badwords

**Comment by mnichols08** [comment]
We  NEED to credit MauriceButler before we forget too
