### ISSUE TITLE
write mobile friendly css for story page

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#58]

**Comment by mnichols08** [comment]
Instructions for getting your project into a proper development state

1. Switch to development branch
```
git checkout development
```
2. Fetch recent changes
```
git fetch
```
3. Pull changes into repo
```
git pull
```
4. Create a new branch following the correct naming convention
```
git branch feat-58/story-page-css/Nazile-Tag
```
5. Switch to your newly created branch
```
git checkout feat-58/story-page-css/Nazile-Tag
```
6. Create a css file
7. Import css file to story.html file
8. Style page to be mobile friendly with css
9. When you are happy with changes made stage them to the repository
```
git add <filename>.<extension>
```
10. Provide an atomic commit message (simply state what is being done in present tense)
```
git commit -m 'styles story page'
```
11. Push your local changes to our repository
```
git push --set-upstream origin feat-58/story-page-css/Nazile-Tag
```
12. Create  pull request to merge your changes into the development branch

**Comment by Nazile-Tag** [comment]
Thank you Mikey

**Comment by mnichols08** [comment]
You are welcome. so happy we got it sorted out XD
