### ISSUE TITLE
Add a navigation bar in the header

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#69]

**Comment by mnichols08** [comment]
At the very least let's put an event listener on the header that will run init() when we click so the user can get back to the main page without refreshing

**Comment by mnichols08** [comment]
I don't know if we really even need this ? We have a link to the team page in the footer, and all docs and whatnot all in the footer...And then the logo takes you home. What do you think guys?

**Comment by mnichols08** [comment]
@Nazile-Tag What do you think?

**Comment by Nazile-Tag** [comment]
@mnichols08 I agree with you. I am working on it and I will share the results with you
