### ISSUE TITLE
Install the Webpack Dependency

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v43-tier1-team-09#98]
In order to minify our code we will want to install a powerful tool called [Webpack](https://webpack.js.org/). It is going to let us write many files but combine everything into a minified (unreadable by most humans) codebase.

To get started we need to simply install a couple of devDependencies. You install these using a `--save-dev` option.
```
npm i webpack webpack-cli concurrently serve --save-dev
```

into your terminal

This should both install the dev dependencies and declare them within the `package.json` file so future users also understand it's requirement

**Bonus** After installing the dependencies, head over to the README.md file and add these packages to the list of Requirements for users. 

We must create a `.gitignore` at this point
and inside it will say or add `node_modules`

otherwise it will want to publish that huge folder which would be no bueno

**Comment by mnichols08** [comment]
If you want to see a snapshot of what this looks like check out a forked version I made here: 
https://github.com/mnichols08/mad-libs/tree/install-webpack

**Comment by PaulaR-05** [comment]
hahaha no bueno

**Comment by PaulaR-05** [comment]
Bueno!
It's working o/
